### ISSUE TITLE
00 -- Here It Comes -- Devan Kestel

### ISSUE THREAD

**Issue by devankestel** [TheIronYard--Orlando/2015--SUMMER--ROR#1]
### Tasks:

Tasks will be rated by Complexity (C), Difficulty (D), and Risk (R). 
- [X] [Create a Github account](https://github.com/signup) [C: S, D: S, R: S]
- [X] [Star the class project](https://github.com/TheIronYard--Orlando/2015--SUMMER--ROR) [C: S, D: S, R: S]
- [X] _5 min_ Read over [the class wiki](https://github.com/TheIronYard--Orlando/2015--SUMMER--ROR/wiki) [C: S, D: S, R: S]
- [X] _5 min_ [Create a new _WIP Issue_](https://github.com/TheIronYard--Orlando/2015--SUMMER--ROR/issues/new) [C: M, D: S, R: S]
  - [X] Named `00 -- Here It Comes -- YOUR NAME` (where `YOUR NAME` is _your_ name)
  - [X] With this checklist as the description
- [x] _5 min_ [Edit your Github profile](https://github.com/settings/profile) to provide:
  - [x] A picture, so I can recognize your face.
  - [x] Your full name, so I can recognize your name.
  - [x] A valid public email address, so I can contact you if I need to.
- [x] _10 min_ Read the `README.md` files in: [C: S, D: S, R: S]
  - [x] [Assignments](https://github.com/TheIronYard--Orlando/2015--SUMMER--ROR/tree/master/Assignments)
  - [x] [Notes](https://github.com/TheIronYard--Orlando/2015--SUMMER--ROR/tree/master/Notes)
- [x] _15 min_ [Install Homebrew](http://brew.sh) on your Mac [C: M, D: S, R: S]
  - [x] Open `Terminal.app`
  - [x] [Install Homebrew and the `brew` command](http://brew.sh/#install)
  - [x] Read [the Homebrew Wiki](https://github.com/Homebrew/homebrew/tree/master/share/doc/homebrew#readme) to learn more about Homebrew
- [x] _10 min_ Using the `brew` command, install the following packages: [C: M, D: M, R: S]
  - [x] `zsh`
  - [x] `git`
  - [x] `hub`
  - [x] `chruby`
  - [x] `ruby-install`
- [x] _10 min_ Using the `ruby-install` command, install Ruby 2.2.2. [C: S, D: S, R: S]
- [x] _5 min_ Set the default version of Ruby to 2.2.2. [C: S, D: L, R: M]
- [x] _10 min_ Add the output of the following commands as comments on your _WIP Issue_: [C: M, D: S, R: S]
  - [x] `which zsh && zsh --version`
  - [x] `which git && git --version`
  - [x] `which hub && hub --version`
  - [x] `which ruby && ruby -v`
- [x] _10 min_ [Install Caskroom](http://caskroom.io) [C: S, D: S, R: S]
- [x] _5 min_ Using `brew cask`, install the following applications: [C: M, D: S, R: S]
  - [x] [Google Chrome](http://google.com/chrome)
  - [x] [Sublime Text](http://sublimetext.com)
  - [x] [Slack](http://www.slack.com)
- NOTE: The above looks like a lot, but those tasks go quickly. The following items require, and deserve, more time. Don't put them off!  
- [x] _10 min_ [Complete the "Hello World" Github guide](https://guides.github.com/activities/hello-world/) [C: S, D: S, R: S]
  - [x] Add a link to your new Github repo as a comment in your WIP Issue.
- [x] _20 min_ Complete the CodeSchool short course, [Try Git](https://www.codeschool.com/courses/try-git)
- [x] _10 min_ Create _another_ new repository called `TIY-Assignments` [C: S, D: S, R: S]
  - [x] Check the box to create an initial `README.md` file
  - [x] Select the `CC0` -- "Creative Commons" license for your work
  - [x] Add a link to your `TIY-Assignments` repo as a comment to your WIP Issue
- [x] _5 min_ [Complete the "Forking Projects" Github guide](https://guides.github.com/activities/forking/) [C: S, D: S, R: S]
  - [x] Add a link to your `Fork-and-Spoon` repo as a comment on your _WIP Issue_
- [x] _10 min_ Install Prezto [C: S, D: S, R: S]
  - [x] Find _and fork_ the Prezto project on Github; add a link as a comment on your _WIP Issue_
  - [x] Use the `hub` command to clone your fork into your home directory as `.zprezto`: `hub clone prezto .zprezto`
- [x] _3 hr_ Read and complete selected exercises for the [Command Line Crash Course] [C: L, D: M, R: S](http://cli.learncodethehardway.org/book/). The command line is another name for the terminal. There are about 10 commands you'll use all the time on the command line, and it's helpful to have them memorized so we can use them right away.  
  - [x] Introduction
  - [x] pwd
  - [x] mkdir
  - [x] cd
  - [x] ls
  - [x] rmdir
  - [x] touch
  - [x] cp
  - [x] mv
  - [x] rm
  - [x] Pipes and Redirection
  - [x] Wildcard Matching
  - [x] What's In Your Environment
  - [x] Changing Environment Variables 
- [x] _20 min_ Read the first four pages about growth vs fixed mindsets at http://mindsetonline.com/whatisit/about/index.html. I'll be honest, this sounded hokey to me when I first read it, but watching how people with the two mindsets performed in previous cohorts, I'm sold on the idea. You have much more control over how much you can learn than you might think. [C: S, D: S, R: S]
- [x] _5 hr_ Read the book [Learn to Program](https://pine.fm/LearnToProgram/). That's a terrific tutorial if you've never written any code before, or if you've never worked with Ruby before. You can read the original version on the author's website for free, or follow the link he gives to purchase the latest version. For this assignment, the exercises in the book are optional. [C: L, D: S, R: S]
  - [x] 0. Getting Started
  - [x] 1. Numbers
  - [x] 2. Letters
  - [x] 3. Variables and Assignment
  - [x] 4. Mixing It Up
  - [x] 5. More About Methods
  - [x] 6. Flow Control
  - [x] 7. Arrays and Iterators
  - [x] 8. Writing Your Own Methods
  - [x] 9. Classes
  - [x] 10. Blocks and Procs
  - [x] 11. Beyond This Tutorial
### Deliverables:
- [x] _WIP Issue_
  - [x] named `00 -- Here It Comes -- YOUR NAME`
  - [x] with description matching **Tasks**
- [x] A Github Profile with:
  - [x] Identifiable picture of yourself
  - [x] Your full name
  - [x] A valid email address
- [x] Comments on your _WIP Issue_ with output from
  - [x] `which zsh && zsh --version`
  - [x] `which git && git --version`
  - [x] `which hub && hub --version`
  - [x] `which ruby && ruby -v`
- [x] Comments on your _WIP Issue_ with links to your repos for
  - [x] `Hello-World`
  - [x] `TIY-Assignments`
  - [x] `Fork-and-Spoon`
  - [x] `prezto`
#### Extracurricular Activities

Regardless of how good you are at typing, a lot of the mistakes you make at first will be simple typographic errors. If you _don't_ know how to touch type (i.e. without looking at the keyboard), start practicing _now_ with http://www.keybr.com/. Typing code is different from typing other documents; more characters are used, and certain letter combinations come up more frequently. If you're fairly confident in your typing ability, try working through the Ruby on Rails lessons on http://typing.io.

There are two books that I suggest you start reading. They're both available in digital format on various devices, and they're both relatively easy reads:
- [_Getting Things Done_ by David Allen](http://j.mp/134jABk)
- [_Pragmatic Thinking and Learning_ by Andy Hunt](http://j.mp/1D5nmu8)

**Comment by devankestel** [comment]
Version Outputs from Terminal:

/usr/local/bin/zsh
zsh 5.0.7 (x86_64-apple-darwin14.0.0)

/usr/local/bin/git
git version 2.4.0

/usr/local/bin/hub
git version 2.4.0
hub version 2.2.1

/Users/devankestel1/.rubies/ruby-2.2.2/bin/ruby
ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin14]

**Comment by devankestel** [comment]
Repo Links: 

https://github.com/devankestel/hello-world

https://github.com/devankestel/TIY-Assignments

https://github.com/devankestel/Spoon-Knife

https://github.com/devankestel/prezto

**Comment by bgates** [comment]
Excellent! I'd close this now, but I think I'll keep it and close it in front of the class in the morning. Good job!
