### ISSUE TITLE
00 -- Here It Comes -- Leslie Brown

### ISSUE THREAD

**Issue by starspace1** [TheIronYard--Orlando/2015--SUMMER--ROR#2]
### Tasks:
- [X] [Create a Github account](https://github.com/signup)
- [X] [Star the class project](https://github.com/TheIronYard--Orlando/2015--SUMMER--ROR)
- [x] _5 min_ Read over [the class wiki](https://github.com/TheIronYard--Orlando/2015--SUMMER--ROR/wiki)
- [x] _5 min_ [Create a new _WIP Issue_](https://github.com/TheIronYard--Orlando/2015--SUMMER--ROR/issues/new)
  - [x] Named `00 -- Here It Comes -- YOUR NAME` (where `YOUR NAME` is _your_ name)
  - [x] With this checklist as the description
- [x] _5 min_ [Edit your Github profile](https://github.com/settings/profile) to provide:
  - [x] A picture, so I can recognize your face.
  - [x] Your full name, so I can recognize your name.
  - [x] A valid public email address, so I can contact you if I need to.
- [x] _10 min_ Read the `README.md` files in:
  - [x] [Assignments](https://github.com/TheIronYard--Orlando/2015--SUMMER--ROR/tree/master/Assignments)
  - [x] [Notes](https://github.com/TheIronYard--Orlando/2015--SUMMER--ROR/tree/master/Notes)
- [x] _15 min_ [Install Homebrew](http://brew.sh) on your Mac
  - [x] Open `Terminal.app`
  - [x] [Install Homebrew and the `brew` command](http://brew.sh/#install)
  - [x] Read [the Homebrew Wiki](https://github.com/Homebrew/homebrew/tree/master/share/doc/homebrew#readme) to learn more about Homebrew
- [x] _10 min_ Using the `brew` command, install the following packages:
  - [x] `zsh`
  - [x] `git`
  - [x] `hub`
  - [x] `chruby`
  - [x] `ruby-install`
- [x] _10 min_ Using the `ruby-install` command, install Ruby 2.2.2.
- [x] _5 min_ Set the default version of Ruby to 2.2.2.
- [x] _10 min_ Add the output of the following commands as comments on your _WIP Issue_:
  - [x] `which zsh && zsh --version`
  - [x] `which git && git --version`
  - [x] `which hub && hub --version`
  - [x] `which ruby && ruby -v`
- [x] _10 min_ [Install Caskroom](http://caskroom.io)
- [x] _5 min_ Using `brew cask`, install the following applications:
  - [x] [Google Chrome](http://google.com/chrome)
  - [x] [Sublime Text](http://sublimetext.com)
  - [x] [Slack](http://www.slack.com)
- NOTE: The above looks like a lot, but those tasks go quickly. The following items require, and deserve, more time. Don't put them off!  
- [x] _10 min_ [Complete the "Hello World" Github guide](https://guides.github.com/activities/hello-world/)
  - [x] Add a link to your new Github repo as a comment in your WIP Issue.
- [x] _20 min_ Complete the CodeSchool short course, [Try Git](https://www.codeschool.com/courses/try-git)
- [x] _10 min_ Create _another_ new repository called `TIY-Assignments`
  - [x] Check the box to create an initial `README.md` file
  - [x] Select the `CC0` -- "Creative Commons" license for your work
  - [x] Add a link to your `TIY-Assignments` repo as a comment to your WIP Issue
- [x] _5 min_ [Complete the "Forking Projects" Github guide](https://guides.github.com/activities/forking/)
  - [x] Add a link to your `Fork-and-Spoon` repo as a comment on your _WIP Issue_
- [x] _10 min_ Install Prezto
  - [x] Find _and fork_ the Prezto project on Github; add a link as a comment on your _WIP Issue_
  - [x] Use the `hub` command to clone your fork into your home directory as `.zprezto`: `hub clone prezto .zprezto`
- [x] _3 hr_ Read and complete selected exercises for the [Command Line Crash Course](http://cli.learncodethehardway.org/book/). The command line is another name for the terminal. There are about 10 commands you'll use all the time on the command line, and it's helpful to have them memorized so we can use them right away.  
  - [x] Introduction
  - [x] pwd
  - [x] mkdir
  - [x] cd
  - [x] ls
  - [x] rmdir
  - [x] touch
  - [x] cp
  - [x] mv
  - [x] rm
  - [x] Pipes and Redirection
  - [x] Wildcard Matching
  - [x] What's In Your Environment
  - [x] Changing Environment Variables 
- [x] _20 min_ Read the first four pages about growth vs fixed mindsets at http://mindsetonline.com/whatisit/about/index.html. I'll be honest, this sounded hokey to me when I first read it, but watching how people with the two mindsets performed in previous cohorts, I'm sold on the idea. You have much more control over how much you can learn than you might think.
- [x] _5 hr_ Read the book [Learn to Program](https://pine.fm/LearnToProgram/). That's a terrific tutorial if you've never written any code before, or if you've never worked with Ruby before. You can read the original version on the author's website for free, or follow the link he gives to purchase the latest version. For this assignment, the exercises in the book are optional.
  - [x] 0. Getting Started
  - [x] 1. Numbers
  - [x] 2. Letters
  - [x] 3. Variables and Assignment
  - [x] 4. Mixing It Up
  - [x] 5. More About Methods
  - [x] 6. Flow Control
  - [x] 7. Arrays and Iterators
  - [x] 8. Writing Your Own Methods
  - [x] 9. Classes
  - [x] 10. Blocks and Procs
  - [x] 11. Beyond This Tutorial
### Deliverables:
- [x] _WIP Issue_
  - [x] named `00 -- Here It Comes -- YOUR NAME`
  - [x] with description matching **Tasks**
- [x] A Github Profile with:
  - [x] Identifiable picture of yourself
  - [x] Your full name
  - [x] A valid email address
- [x] Comments on your _WIP Issue_ with output from
  - [x] `which zsh && zsh --version`
  - [x] `which git && git --version`
  - [x] `which hub && hub --version`
  - [x] `which ruby && ruby -v`
- [x] Comments on your _WIP Issue_ with links to your repos for
  - [x] `Hello-World`
  - [x] `TIY-Assignments`
  - [x] `Fork-and-Spoon`
  - [x] `prezto`

**Comment by starspace1** [comment]
Leslies-MacBook:~ lesliebrown$ which zsh && zsh --version
/usr/local/bin/zsh
zsh 5.0.7 (x86_64-apple-darwin14.0.0)

Leslies-MacBook:~ lesliebrown$ which git && git --version
/usr/local/bin/git
git version 2.4.0

Leslies-MacBook:~ lesliebrown$ which hub && hub --version
/usr/local/bin/hub
git version 2.4.0
hub version 2.2.1

Leslies-MacBook:~ lesliebrown$ which ruby && ruby -v
/usr/bin/ruby
ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14] <--needs to be 2.2.2

**Comment by starspace1** [comment]
https://github.com/starspace1/hello-world

**Comment by starspace1** [comment]
https://github.com/starspace1/TIY-Assignments

**Comment by starspace1** [comment]
https://github.com/starspace1/Spoon-Knife

**Comment by starspace1** [comment]
https://github.com/starspace1/prezto

**Comment by letrado** [comment]
https://github.com/letrado/hello-world

**Comment by bgates** [comment]
Ah, the dreaded system Ruby! `chruby` isn't getting the job done. See if you get any output from 
`$ chruby`
and we'll go from there.

The GitHub practice looks like it went well, so just the default Ruby to take care of.

**Comment by starspace1** [comment]
Fixed. Just had to add the following to the bottom of the .zprofile file:

**source /usr/local/share/chruby/chruby.sh**
**chruby ruby-2.2.2**
