### ISSUE TITLE
07-TodoMVC1-Erik Jenks

### ISSUE THREAD

**Issue by erikjenks** [TheIronYard--Orlando/2015--SUMMER--ROR#66]
# ToDo List
- [x] Directory Structure

```
index.html.erb
public/
├── index.css
├── app.js
todo_controller.rb
todo.rb
setup.rb
readme.md
```
- [ ] Code

Refer to the comments in the HTML for guidance on how the evaluated template should look in different circumstances. 
- [ ] Functionality
  - [x] No todos
  - [x] When there are no todos, `#main` and `#footer` should be hidden.
  - [x] New todo
  - [x] New todos are entered in the input at the top of the app. 
  - [x] The input element should be focused when the page is loaded preferably using the `autofocus` input attribute. 
  - [x] Pressing Enter creates the todo, appends it to the todo list and clears the input. 
  - [x] Make sure to `.trim()` the input and then check that it's not empty before creating a new todo.
- [x] Toggle all completeness
  - [x] This checkbox sets all the todos to have the same complete status. If any or all todo items are incomplete, clicking this checkbox will set all todos to be complete. 
  - [x] If all todo items are complete, clicking this checkbox
    will set all todos to be incomplete. 
- [ ] Item
  - [x] A todo item has three possible interactions:
    - [x] Clicking the checkbox toggles the todo's completeness status. 
    - [x] A checkbox's parent `<li>` has the class `completed` if and only if the todo is complete.
    - [ ] Clicking the `<a>` which displays the name of a todo activates editing mode for that todo.
    - [ ] If a todo is being edited, its `<li>` will have the class `editing`. 
    - [x] Hovering over the todo shows the remove button (`.destroy`). and clicking a remove button for a todo destroys that todo.
- [ ] Editing
  - [ ] When editing mode is activated for a todo the other controls for that todo (the checkbox, edit link, and remove button) will be hidden. 
  - [ ] In their place will be an input that contains the todo title, which should be focused when the page loads. 
  - [ ] Submitting the form to update the todo title should save the title and return the app to the main `todos` page.
  - [ ] No todo should have the `editing` class on the main `todos` page. 
  - [ ] Remove leading and trailing whitespace from the title (ie, change `"    this   "` to `"this"`).
  - [ ] If a todo is updated to have a blank title, the todo should be destroyed instead of saved. 
- [x] Counter
  - [x] Displays the number of active todos in a pluralized form. 
  - [x] Make sure the number is wrapped by a `<strong>` tag. 
  - [x] Also make sure to pluralize the `item` word correctly: `0 items`, `1 item`, `2 items`. Example: **2** items left
- [x] Clear completed button
  - [x] Destroys all completed todos when clicked. 
  - [x] Should be hidden when there are no completed todos.
- [x] Persistence
  - [x] Your app should dynamically persist the todos to a database created by running `setup.rb`.  
- [ ] Routing
  - [x] Every route (link URL and form action) that shows up in the template must be handled by a code block in  `todos_controller.rb` (which is the server file for this app). 
  - [x] Every route that renders a template uses the same template. 
  - [x] Some routes redirect instead of rendering.
  - [x] The following routes should be implemented: 
    - [x]  `/todos` (all - default)
    - [x]  `/active` 
    - [x]  `/completed` 
  - [x] You should also have routes to handle each of the actions described in the functionality section:
    - [x]  creating a new todo
    - [x]  toggling all completeness
    - [x]  destroying all complete todos
    - [x]  editing a particular todo (that is, showing the edit form for that todo)
    - [x]  updating a particular todo (that is, saving the changes in its name to the database)
    - [x]  toggling a particular todo's completeness
    - [x]  destroying a particular todo
- [ ] Beast Mode
  - [x] Add a category field to your todos table, along with the name and complete fields. 
  - [ ] Add a separate page listing a few predetermined categories (IronYard, Personal, Relationship, whatever).
  - [ ] A user should have a fully functioning todo list for each of the categories you allow. 
  - [ ] A todo item created in the context of a list should be assigned to the category of that list. 
  - [ ] Toggling all or destroying all complete items should also be scoped to the context of 
    that list. 
  - [ ] There should be links to navigate from one list to another.
- [ ] Nightmare Mode
  - [ ] Add the capability to track due dates for each todo item. 
  - [ ] A user could enter a due date in the same text box as the name - for instance, "finish weekend project -- 05/31". 
  - [ ] Work through css classes to have visual indications for which tasks are due in the future, due today, or overdue. 
  - [ ] Add a filtering link to sort todo items by due date.
  - [ ] If you want to really go nuts, see if you can do some light natural language processing and get away with entering names like "finish weekend project -- Sunday" or "5 mi run -- tomorrow".

**Comment by erikjenks** [comment]
https://github.com/ejenks/TIY-Assignments/pull/8
